var innerOffset = 10;
var fieldOffset = 43;
var fieldWidthOffset = innerOffset * 2;
var linkItemSize = 10;
var fieldItemWidth = 160;
var fieldItemHeight = 25;
var tascItemWidth = 180;
var tascItemHeight = 250;
var xOffset= 10;
var yOffset= 10;
var svgURI = 'http://www.w3.org/2000/svg';

var paths = [];
var tascItems = [];
var fieldItems = [];
var tascData = [];
var fieldData = [];
var svgHistory = [];
var svgHistoryIndex = 1;